import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — NowIGet",
  description: "Terms and conditions for using NowIGet.",
};

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-full">
      <nav className="fixed top-0 left-0 right-0 z-50 bg-card-bg/90 backdrop-blur-md border-b border-border/50">
        <div className="max-w-[1200px] mx-auto px-6 flex items-center justify-between h-16">
          <a href="/" className="text-xl font-bold tracking-tight text-foreground">
            Now<span className="text-primary">I</span>Get
          </a>
          <a href="/" className="text-sm text-secondary hover:text-foreground transition-colors">
            ← Back to home
          </a>
        </div>
      </nav>

      <main className="pt-28 pb-20 px-6">
        <div className="max-w-[720px] mx-auto">
          <h1 className="text-3xl md:text-4xl font-extrabold text-foreground mb-2">Terms of Service</h1>
          <p className="text-secondary/60 text-sm mb-12">Last updated: April 2026</p>

          <div className="space-y-10 text-[15px] text-foreground leading-relaxed">

            <section>
              <h2 className="text-lg font-bold text-foreground mb-3">Using NowIGet</h2>
              <p className="text-secondary">
                NowIGet is a free tool for getting clear explanations of things you are confused about. By using this service, you agree to use it responsibly and in good faith. You may not use NowIGet to generate harmful, illegal, or abusive content.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-foreground mb-3">AI-generated content</h2>
              <p className="text-secondary">
                All explanations on NowIGet are generated by artificial intelligence. While we aim for accuracy, AI can make mistakes. Do not rely on NowIGet for medical, legal, financial, or safety-critical decisions. Always consult a qualified professional for these matters.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-foreground mb-3">Public explanations</h2>
              <p className="text-secondary">
                When you submit a general knowledge question, the question and its AI-generated answer may be published as a permanent public page and indexed by search engines. By submitting a question, you agree to this. Do not submit questions containing personal information you do not want published.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-foreground mb-3">Accuracy and liability</h2>
              <p className="text-secondary">
                NowIGet makes no warranties about the accuracy, completeness, or reliability of AI-generated explanations. We are not liable for any decisions made based on content generated by this service. Use your own judgment and verify important information with authoritative sources.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-foreground mb-3">Reporting content</h2>
              <p className="text-secondary">
                Every public explanation page has a &ldquo;Report this page&rdquo; button. If you find content that is inaccurate, harmful, or inappropriate, please use it. We review reported content and remove or correct it as needed.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-foreground mb-3">Changes to the service</h2>
              <p className="text-secondary">
                We may update, modify, or discontinue NowIGet at any time without notice. We may also update these terms — continued use of the service after changes means you accept the new terms.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-foreground mb-3">Contact</h2>
              <p className="text-secondary">
                Questions about these terms? Contact us at <span className="text-primary">hello@nowiget.com</span>.
              </p>
            </section>

          </div>
        </div>
      </main>

      <footer className="py-10 px-6 border-t border-border/40 text-center">
        <p className="text-xs text-secondary/40">
          &copy; {new Date().getFullYear()} Now<span className="text-primary font-semibold">I</span>Get. All rights reserved.
        </p>
      </footer>
    </div>
  );
}
